#!/bin/bash
service neutron-linuxbridge-agent stop
apt-get -o Dpkg::Options::="--force-confold" -y install --only-upgrade neutron-plugin-ml2 neutron-linuxbridge-agent
service neutron-linuxbridge-agent start
