#!/bin/bash
dir_path=$(dirname $0)
bash $dir_path/../haproxy/disable_server.sh neutron_api controller1
sleep 10

service neutron-server stop
sleep 2
apt-get -o Dpkg::Options::="--force-confold" -y install --only-upgrade neutron-server neutron-plugin-ml2
sleep 2
neutron-db-manage upgrade --expand
service neutron-server start

sleep 5

bash $dir_path/../haproxy/enable_server.sh neutron_api controller1
sleep 10

